language: java
jdk:
 - openjdk7

branches:
  only:
    - develop
    - master

cache: true

env: 
  global: 
   #SLACK_URLPATH
   - secure: BHaKpcpdCwMO7xWQFkLD5XVBPH34cEnr7rZu9KnzAcqLIFJP0rdGDGOXSGF1u7PlNm3blxvEbyBTPE3nDJ6eJKKltffpHv215UIBifV3uRGJ2EimvKNaHwE+ZYaMFq5S7Wxszjn+ALd0hni6/baBAMexXz4cb8mHDvK2FDKc1OH17DnAyyvV6t7n0RScnjJEMsqN5cvleU/HEqsbsFTNwdvWNs1nQHI5qC6yz5PCvaGmjVKF7bGVkaWrGNYuMibVcpURLlpAx3BDwXXfaZZuJCGBp48fdPIqfxgi8LTa1wNeqKcr9hbb/zklPsL2d67s6YcZ5c/JjstSU0BH214GUA==
   #MVN_REPO_PASS
   - secure: GpJEx7CrMY6InNkC9+onefTcf6S/2kZv6cTe/r1NG8HfIoCIPQkJ8R0uZYTmHDlWAIYlbdK0ZMJh+Atjpe9k3WoQ8R8tKNjnugpYQ+44tjBaBsueNopxi8gnCdu4gzgBTI7JYz3603RJNehpJtlNuSlDKa32wTw90pWSNAnXgoAVsK4kb551mK7I1P8SK2TZOObIRpbXY4RLbkWrdmHdAh7gd8SAcmT1xCu6tZR+ErVm5kHg62P9r9q2se0MdaAIvfasYnctAoqc9JoCdFEnXUQglzKzzPSAC+9jRHtez9OR8KYGabihRNOo1BbGXPRg+4Lt8iUgy5mBVUAHSw7BWg==
   #MVN_REPO_PASS_WRITE
   - secure: YV90fY2zHfEt1HNC2sh/WmxpjdTBRnYAS5YT0uTSUKwnpRo0mwh8U0P4z5tvVVqGjeBP6X9gRzvOXWb5coCRHbT8yzsqem5OEMcxxM+SKzda1izBXDYD5fu+HwVqZbniX2IxzglDtQNn9/sEXyU4RHJZ7lTyByzeyco3xt+ex7ZVtkqo1eKnIACyirlqM7NcmuCeWVQc/Zh8U6hQm0XVKexOxDwaB8SyQQBquMP91pgp0tuaIcoDlvIMen6E7sWqSyGwflZuKR9dIknHXpL/VrNzT8t75NeDeyTYzZP4+t/k2Tw0rnTD84f7BMDcBX3Ujqg5XOyqjq7IlOaqKvkJ4w==
   - SLACK_ORG=37coins 
   - PROJECT=clx-java

after_success : 
   - bash  set_mvn_settings_libs.bash $MVN_REPO_PASS $MVN_REPO_PASS_WRITE
   - python slack_notifier_new.py --project $PROJECT --org $SLACK_ORG --urlpath $SLACK_URLPATH -s 
   - mvn clean deploy -DskipTests

after_failure :
   - python slack_notifier_new.py --project $PROJECT --org $SLACK_ORG --urlpath $SLACK_URLPATH

notifications:
    email:
      recipients:
        - dev@37coins.com
      on_success: always
      on_failure: change
